import Image from "next/image";
import { ArrowDown, ArrowUpRight, MapPin, Sparkles } from "lucide-react";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { ContactLinks } from "@/components/contact-links";
import { readDatabase } from "@/lib/store";
export const dynamic = "force-dynamic";
export default async function Home() {
  const { settings } = await readDatabase();
  return <div className="site-shell"><Header /><main><section className="home-grid"><div className="hero-photo"><Image src="/images/hero.png" alt="A sunlit living room with an ivory sofa, walnut accents and timeless natural textures" fill priority sizes="(max-width: 800px) 100vw, 53vw" className="hero-image" /><div className="photo-shade" /><span className="photo-label"><span className="little-dot" /> THE DRAVOHOME WAY</span><div className="photo-copy"><span className="photo-eyebrow">THOUGHTFUL FURNITURE. BEAUTIFUL SPACES.</span><h2>For the moments<br />that make a <em>home.</em></h2><div className="photo-bottom"><span>Considered design. Effortless living.</span><span className="circle-arrow"><ArrowUpRight size={23} strokeWidth={1.3} /></span></div></div><span className="photo-index">01 / THE ART OF LIVING</span></div><div className="home-content"><div className="welcome-eyebrow"><span /> WELCOME TO DRAVOHOME</div><h1>Make yourself<br />at <em>home.</em><span className="heading-star"><Sparkles size={29} strokeWidth={1} /></span></h1><p className="home-intro">Furniture with feeling. Spaces with soul.<br />Your next chapter of beautiful living starts here.</p><ContactLinks settings={settings} /><div className="home-note"><span className="little-dot" /> A little inspiration. A world of possibilities.</div></div></section><section className="brand-strip"><div className="strip-intro"><span className="eyebrow">CURATED WITH CARE</span><span>Every room. Every feeling.</span></div><div className="strip-collections"><span>Living</span><span className="collection-divider" /><span>Dining</span><span className="collection-divider" /><span>Bedroom</span><span className="collection-divider" /><span>Outdoor</span></div><a className="strip-explore" href="#experience">Discover DravoHome <ArrowDown size={16} /></a></section><section className="experience-section" id="experience"><div className="experience-title"><span className="eyebrow">MORE THAN A SHOWROOM</span><h2>Come for the furniture.<br /><em>Stay for the feeling.</em></h2></div><div className="experience-details"><p>Touch the textures. Find your favourite corner. Imagine what’s possible. Our experience centre brings beautiful design a little closer to home.</p>{settings.address ? <div className="address-line"><MapPin size={18} strokeWidth={1.4} /><div><span>{settings.address}</span>{settings.hours && <small>{settings.hours}</small>}</div></div> : <div className="experience-signature"><span className="little-dot" /> Thoughtfully selected. Made to be lived in.</div>}</div></section></main><Footer /></div>;
}
