"use client";
import { useState } from "react";
import Image from "next/image";
import { ArrowUpRight, BookOpen, Download, Search, X } from "lucide-react";
import { categories, type Brochure } from "@/lib/types";
import { formatSize } from "@/lib/format";
export function BrochureLibrary({ brochures }: { brochures: Brochure[] }) {
  const [category, setCategory] = useState("All collections");
  const [query, setQuery] = useState("");
  const shown = brochures.filter(item => (category === "All collections" || item.category === category) && `${item.title} ${item.description} ${item.category}`.toLowerCase().includes(query.trim().toLowerCase()));
  return <><div className="library-toolbar"><div className="category-tabs" aria-label="Filter brochures">{["All collections", ...categories].map(item => <button aria-pressed={category === item} className={category === item ? "active" : ""} key={item} onClick={() => setCategory(item)}>{item}</button>)}</div><label className="search-field"><Search size={16} /><span className="sr-only">Search brochures</span><input type="search" value={query} onChange={event => setQuery(event.target.value)} placeholder="Find your collection" /></label></div><div className="library-result-count" aria-live="polite"><span>{shown.length} {shown.length === 1 ? "brochure" : "brochures"}</span><span>THOUGHTFULLY CURATED FOR YOU</span></div>{shown.length ? <div className="brochure-grid">{shown.map((item, index) => <article className="brochure-card" key={item.id}><a className={`brochure-cover cover-${item.category.toLowerCase().split(" ")[0]}`} href={`/api/brochures/${item.id}`} target="_blank" rel="noopener noreferrer" aria-label={`View ${item.title} PDF`}><Image src="/images/hero.png" alt="Warm furniture and natural textures" fill sizes="(max-width: 600px) 100vw, (max-width: 1000px) 50vw, 33vw" /><span className="cover-overlay" /><span className="cover-top">dravo<span>home</span><span>COLLECTION {String(index + 1).padStart(2, "0")}</span></span><span className="cover-title"><span>{item.category.toUpperCase()}</span><strong>{item.title}</strong><span className="cover-rule" /></span><span className="cover-pdf">EXPLORE THE COLLECTION <ArrowUpRight size={17} /></span></a><div className="brochure-info"><span className="eyebrow">{item.category}</span><h2>{item.title}</h2><p>{item.description || "Thoughtful pieces to make your space feel like home."}</p><div className="brochure-actions"><a href={`/api/brochures/${item.id}`} target="_blank" rel="noopener noreferrer">View brochure <ArrowUpRight size={16} /></a><a href={`/api/brochures/${item.id}?download=1`} className="download-link" aria-label={`Download ${item.title}`}><Download size={16} /><span>{formatSize(item.size)}</span></a></div></div></article>)}</div> : <div className="library-empty"><span className="empty-icon"><BookOpen size={34} strokeWidth={1} /></span><span className="eyebrow">{brochures.length ? "A FRESH PERSPECTIVE" : "SOMETHING BEAUTIFUL IS ON ITS WAY"}</span><h2>{brochures.length ? "Let’s find your inspiration." : "Good things take a little care."}</h2><p>{brochures.length ? "No brochures match your search. Try another collection or a different word." : "Our latest brochures are being thoughtfully curated. Check back soon for a closer look at the DravoHome collections."}</p>{brochures.length > 0 && <button className="text-button" onClick={() => { setCategory("All collections"); setQuery(""); }}>Clear filters <X size={15} /></button>}</div>}</>;
}
